#!/usr/bin/env node
/**
 * Renders the live prompt library into src/partials/prompt-library.html.
 *
 *   npm run prompts
 *
 * Source of truth is the app's own seed file, not a copy typed into this repo:
 *
 *   ../Project-Rascal/api/seeds/prompts.yaml
 *
 * Two things make this a codegen step rather than a paste.
 *
 * 1. THE TOKENS. Library bodies store {they} {them} {their} {theirs} {themself},
 *    the agreement compounds {they_are} {they_were} {they_have} {they_do}, the
 *    capitals {They} {Them} {Their}, and {name} — thirteen, rendered at display
 *    time. The table below is the one from
 *    Project-Rascal/api/src/rascal/export_viewer/assets/app.js, copied with its
 *    invariants intact rather than reimplemented. seo-plan.md marks this row
 *    Critical: a literal "{their}" indexed on the page whose whole job is
 *    proving the prompts are well written fails silently and publicly.
 *
 *    The site has no child, so it renders the they/them column — which is
 *    grammatical for every child and is not a guess at an answer nobody gave —
 *    and a neutral stand-in for {name}.
 *
 * 2. SERVER-RENDERED. The output is static HTML with the data on the elements,
 *    so the page is complete before any script runs and the filters are a
 *    progressive enhancement over markup that already ranks.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SEED = process.env.PROMPT_SEED || join(root, '..', 'Project-Rascal', 'api', 'seeds', 'prompts.yaml');
const OUT = join(root, 'src', 'partials', 'prompt-library.html');

/* ------------------------------------------------------- the token table */
/* Verbatim from export_viewer/assets/app.js. Do not write a second one. */
const PRONOUN_COLUMN = {
  'they/them': {
    they: 'they', them: 'them', their: 'their', theirs: 'theirs', themself: 'themself',
    they_are: 'they are', they_were: 'they were', they_have: 'they have', they_do: 'they do',
    They: 'They', Them: 'Them', Their: 'Their'
  }
};
const pronouns = PRONOUN_COLUMN['they/them'];

/* site-content.md: "a neutral stand-in for {name}". All ten {name} bodies read
   naturally with this one — "What is your kid obsessed with right now?" */
const NAME_STANDIN = 'your kid';

function renderTokens(body) {
  if (body.indexOf('{') === -1) return body;        // invariant 1: byte-identical
  let out = '';
  let cursor = 0;
  for (;;) {
    const open = body.indexOf('{', cursor);
    if (open === -1) break;
    const close = body.indexOf('}', open + 1);
    if (close === -1) break;                        // unclosed brace is literal text
    const token = body.slice(open + 1, close);
    let value = null;
    if (token === 'name') value = NAME_STANDIN;
    else if (Object.prototype.hasOwnProperty.call(pronouns, token)) value = pronouns[token];
    out += body.slice(cursor, open);
    // invariant 3: an unknown token renders literally, braces and all
    out += value === null ? body.slice(open, close + 1) : value;
    cursor = close + 1;
  }
  return out + body.slice(cursor);
}

/* ------------------------------------------------------------ yaml parse */
/* prompts.yaml is generated by scripts/mission_library_to_yaml.py and has a
   fixed shape: a flat sequence of maps of scalars, plus one block list. That is
   narrow enough to parse honestly in thirty lines and loud enough to fail if
   the shape ever changes, which beats taking a dependency on a full parser. */
function parseSeed(text) {
  const items = [];
  let cur = null;
  let listKey = null;
  let lastKey = null;
  for (const rawLine of text.split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line || /^\s*#/.test(line)) continue;

    if (line.startsWith('- ')) {                    // new record
      cur = {};
      items.push(cur);
      listKey = null;
      lastKey = applyPair(cur, line.slice(2));
      continue;
    }
    if (!cur) throw new Error(`seed: content before the first record — ${line}`);

    const item = line.match(/^\s*-\s+(.*)$/);       // block-list entry
    if (item) {
      if (!listKey) throw new Error(`seed: list entry with no key — ${line}`);
      cur[listKey].push(coerce(item[1]));
      continue;
    }
    const kv = line.match(/^\s{2}([a-z_]+):\s*(.*)$/);
    if (kv) {
      if (kv[2] === '') { listKey = kv[1]; lastKey = null; cur[listKey] = []; continue; }
      listKey = null;
      lastKey = applyPair(cur, `${kv[1]}: ${kv[2]}`);
      continue;
    }

    /* A plain scalar that wrapped. Six of the bodies are long enough that the
       generator folded them, and YAML joins a folded continuation with a single
       space — dropping it would silently truncate a prompt mid-sentence. */
    const cont = line.match(/^\s{4,}(\S.*)$/);
    if (cont && lastKey && typeof cur[lastKey] === 'string') {
      cur[lastKey] += ' ' + cont[1];
      continue;
    }
    throw new Error(`seed: unparsed line — ${line}`);
  }
  return items;
}
function applyPair(obj, s) {
  const kv = s.match(/^([a-z_]+):\s*(.*)$/);
  if (!kv) throw new Error(`seed: unparsed pair — ${s}`);
  obj[kv[1]] = kv[2] === '[]' ? [] : coerce(kv[2]);
  return kv[1];
}
function coerce(v) {
  if (v === 'null' || v === '~') return null;
  if (v === 'true') return true;
  if (v === 'false') return false;
  if (/^-?\d+$/.test(v)) return Number(v);
  return v.replace(/^["'](.*)["']$/, '$1');
}

/* ---------------------------------------------------------- presentation */
/* Kind → tint follows the app: questions and voice are periwinkle, anything
   that asks you to go make something is terracotta, and the measurement
   missions are sage because what they produce is a completed fact, not media. */
const KIND = {
  question:    { label: 'Question',    tone: 'peri',  chip: 'chip--peri' },
  audio:       { label: 'Voice',       tone: 'peri',  chip: 'chip--peri' },
  photo:       { label: 'Photo',       tone: 'terra', chip: 'chip--terra' },
  video:       { label: 'Video',       tone: 'terra', chip: 'chip--terra' },
  activity:    { label: 'Activity',    tone: 'terra', chip: 'chip--terra' },
  letter:      { label: 'Letter',      tone: 'terra', chip: 'chip--terra' },
  measurement: { label: 'Measurement', tone: 'sage',  chip: 'chip--sage' }
};
const SHAPE = { media: 'Captured it', text: 'Wrote it', did_it: 'Did it' };
const BANDS = [
  { key: '2-3',  label: 'Ages 2–3',  min: 24,  max: 47 },
  { key: '4-5',  label: 'Ages 4–5',  min: 48,  max: 71 },
  { key: '6-8',  label: 'Ages 6–8',  min: 72,  max: 107 },
  { key: '9-12', label: 'Ages 9–12', min: 108, max: 155 },
  { key: '13+',  label: 'Ages 13+',  min: 156, max: 300 }
];
const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* ----------------------------------------------------------------- build */
const seed = await readFile(SEED, 'utf8').catch(() => {
  throw new Error(
    `cannot read the prompt seed at:\n  ${SEED}\n` +
    `Set PROMPT_SEED to its path, or check out Project-Rascal beside this repo.`
  );
});

const all = parseSeed(seed).filter((p) => p.active !== false);
if (!all.length) throw new Error('seed parsed to zero active prompts');

/* ---------------------------------------------------------- stable anchors */
/* seo-plan.md rates per-prompt anchors High severity, and an anchor that
   renumbers when a prompt is deactivated or reordered breaks every link
   anyone ever shared. So the id is not the position: each prompt's raw body
   is hashed, and the hash → p-NNNN assignment is persisted in
   scripts/prompt-anchors.json. New prompts get the next free number; retired
   prompts keep their number reserved forever, so nothing ever shifts. */
const ANCHORS = join(root, 'scripts', 'prompt-anchors.json');
const { createHash } = await import('node:crypto');
const anchorKey = (p) => createHash('sha256').update(`${p.kind}|${p.body}`).digest('hex').slice(0, 12);

let anchorMap = {};
try {
  anchorMap = JSON.parse(await readFile(ANCHORS, 'utf8'));
} catch {}
let nextNum = Object.values(anchorMap).reduce(
  (m, id) => Math.max(m, parseInt(id.slice(2), 10)), 0
);
for (const p of all) {
  const key = anchorKey(p);
  if (!anchorMap[key]) anchorMap[key] = 'p-' + String(++nextNum).padStart(4, '0');
}
await writeFile(ANCHORS, JSON.stringify(anchorMap, null, 2) + '\n');

/* ------------------------------------------------------------- the weave */
/* The seed is grouped by kind, which is right for the seed and wrong for a
   page: read top to bottom it opened with thirty questions in a row, so the
   unfiltered library looked like a question-only library until you scrolled
   past ten rows of periwinkle.
 *
 * So the render order is woven instead. Each kind is spread evenly across the
 * whole list by its own fraction — a prompt sits at (i + 0.5) / n of the way
 * down, and everything sorts on that — which puts the 43 photos every third
 * card and the 3 measurements at a sixth, a half and five sixths. Ties break
 * on the KIND table's order so the output is deterministic: same seed, same
 * page, every build.
 *
 * Two things make this safe to do. Anchors are content-hashed, not positional,
 * so nothing anyone linked to moves. And within a kind the seed's order is
 * preserved exactly, so picking a filter still reads in the authored order. */
const KIND_ORDER = Object.keys(KIND);
function weave(items) {
  const groups = new Map();
  for (const p of items) {
    if (!groups.has(p.kind)) groups.set(p.kind, []);
    groups.get(p.kind).push(p);
  }
  const placed = [];
  for (const [kind, list] of groups) {
    list.forEach((p, i) => placed.push({ p, kind, at: (i + 0.5) / list.length }));
  }
  placed.sort((a, b) => a.at - b.at || KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind));
  return placed.map((x) => x.p);
}

const kindCounts = {};
const bandCounts = {};
const cards = [];

weave(all).forEach((p) => {
  const meta = KIND[p.kind];
  if (!meta) throw new Error(`unknown prompt kind "${p.kind}" — add it to the KIND table`);

  const body = renderTokens(String(p.body));
  if (/\{[A-Za-z_]+\}/.test(body)) {
    throw new Error(
      `unrendered token in the ${p.kind} prompt: "${body}"\n` +
      `Every token must be in the table above. This is the Critical row in seo-plan.md.`
    );
  }

  const bands = BANDS.filter((b) => p.min_age_months <= b.max && p.max_age_months >= b.min);
  kindCounts[p.kind] = (kindCounts[p.kind] || 0) + 1;
  bands.forEach((b) => { bandCounts[b.key] = (bandCounts[b.key] || 0) + 1; });

  const id = anchorMap[anchorKey(p)];
  const cadence = p.cadence === 'daily' ? '' : `<span class="t-meta">${esc(p.cadence)}</span>`;
  const sealed = p.default_unlock_age ? `<span class="chip chip--md">Opens at ${p.default_unlock_age}</span>` : '';

  cards.push(
`<article class="prompt prompt--${meta.tone}" id="${id}" data-kind="${esc(p.kind)}" data-bands="${bands.map((b) => b.key).join(' ')}">
  <div class="prompt__head">
    <span class="chip ${meta.chip}">${meta.label}</span>
  </div>
  <p class="prompt__body">${esc(body)}</p>
  <p class="prompt__meta">
    <span class="t-meta">${SHAPE[p.completion_mode] || p.completion_mode}</span>
    ${cadence}${sealed}
  </p>
</article>`
  );
});

/* No counts on the pills. They were four kinds of noise at once: the total is
   already in the H1 and the lede, "Ages 4–5 133" says nothing because almost
   every prompt spans almost every band, and a number baked into a label is a
   number that has to be re-rendered to stay true. The live count below the
   filters is the honest one — it counts what you are actually looking at. */
const kindFilters = Object.entries(KIND)
  .filter(([k]) => kindCounts[k])
  .map(([k, m]) =>
    `<button class="filter" type="button" data-filter="kind" data-value="${k}" aria-pressed="false">${m.label}</button>`
  ).join('\n      ');

const bandFilters = BANDS
  .filter((b) => bandCounts[b.key])
  .map((b) =>
    `<button class="filter" type="button" data-filter="band" data-value="${b.key}" aria-pressed="false">${b.label}</button>`
  ).join('\n      ');

/* data-chrome marks the filter UI as chrome for the Markdown twins: the pills
   are already dropped as <button>s, but "Showing all 133 prompts." is not
   content either, and neither is an empty state nobody has triggered. */
const html = `<!-- GENERATED by scripts/prompts.mjs — do not edit by hand.
     Source: ${SEED.replace(root, '.')}
     ${all.length} active prompts, pronoun tokens rendered from the they/them column,
     woven across kinds so the unfiltered page does not open on thirty questions. -->
<div class="plib__bar" id="prompt-filters" data-chrome>
  <div class="wrap stack gap-12">
    <div class="filters" role="group" aria-label="Filter prompts by kind">
      <button class="filter" type="button" data-filter="kind" data-value="" aria-pressed="true">All</button>
      ${kindFilters}
    </div>
    <div class="filters" role="group" aria-label="Filter prompts by age">
      <button class="filter" type="button" data-filter="band" data-value="" aria-pressed="true">Every age</button>
      ${bandFilters}
    </div>
    <div class="plib__find">
      <label class="plib__search">
        <span class="vh">Search the prompts</span>
        <input type="search" data-prompt-query placeholder="Search for a word — laugh, bedtime, school"
               autocomplete="off" autocorrect="off" spellcheck="false" enterkeyhint="search">
      </label>
      <p class="plib__count" role="status" data-prompt-count></p>
    </div>
  </div>
</div>

<div class="wrap">
  <div class="plib" id="prompt-list">
${cards.join('\n')}
  </div>
  <p class="plib__empty t-body muted" data-prompt-empty data-chrome hidden>
    Nothing matches that. <button class="btn--text" type="button" data-prompt-reset>Clear the filters</button>
  </p>
</div>
`;

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, html);

/* ------------------------------------------------- the home page's copies */
/* The marquee and the deck read the same rendered library rather than a second
   list typed into the markup. A hand-kept copy is how a raw {their} reaches
   production on the one page that exists to prove the prompts are well written. */

const rendered = all.map((p) => ({ ...p, text: renderTokens(String(p.body)) }));
const pick = (kind, n, offset = 0) => rendered.filter((p) => p.kind === kind).slice(offset, offset + n);

/* A spread across kinds, so the strip never reads as one long list of photos. */
const stripA = [
  ...pick('question', 3), ...pick('photo', 2), ...pick('audio', 2),
  ...pick('activity', 2), ...pick('video', 1)
];
const stripB = [
  ...pick('question', 3, 3), ...pick('photo', 2, 2), ...pick('letter', 2),
  ...pick('activity', 2, 2), ...pick('measurement', 1)
];

const strip = (items) => items.map((p) => {
  const m = KIND[p.kind];
  const tone = m.tone === 'sage' ? '' : ` pcard--${m.tone}`;
  return `<div class="pcard${tone}">
  <span class="chip ${m.chip}">${m.label}</span>
  <p class="pcard__body">${esc(p.text)}</p>
</div>`;
}).join('\n');

await writeFile(join(root, 'src', 'partials', 'marquee-a.html'), strip(stripA) + '\n');
await writeFile(join(root, 'src', 'partials', 'marquee-b.html'), strip(stripB) + '\n');

/* The deck. For an imperative mission the first word is the instruction, so it
   carries the kind's ink; a question has no verb to lift and stays plain. */
const deck = rendered.map((p) => {
  const m = KIND[p.kind];
  const imperative = p.kind !== 'question';
  const cut = imperative ? p.text.indexOf(' ') : -1;
  return [
    m.label.toUpperCase(),
    m.tone,
    cut > 0 ? p.text.slice(0, cut) : '',
    cut > 0 ? p.text.slice(cut) : p.text
  ];
});

await writeFile(
  join(root, 'src', 'assets', 'deck.js'),
  `/* GENERATED by scripts/prompts.mjs — do not edit by hand.\n` +
  `   ${deck.length} prompts, pronoun tokens already rendered. */\n` +
  `window.DECK = ${JSON.stringify(deck)};\n`
);

console.log(`prompts: ${all.length} rendered → src/partials/prompt-library.html`);
console.log(`  marquee: ${stripA.length} + ${stripB.length} cards, deck: ${deck.length} cards`);
console.log(`  kinds: ${Object.entries(kindCounts).map(([k, n]) => `${k} ${n}`).join(', ')}`);
console.log(`  bands: ${BANDS.filter((b) => bandCounts[b.key]).map((b) => `${b.label} ${bandCounts[b.key]}`).join(', ')}`);
console.log(`  tokens: all rendered, no literal braces survived`);
const config = JSON.parse(await readFile(join(root, 'site.config.json'), 'utf8'));
if (String(all.length) !== String(config.PROMPT_COUNT)) {
  console.log(`  ! PROMPT_COUNT is ${config.PROMPT_COUNT} in site.config.json but the library has ${all.length} — update it`);
  process.exitCode = 1;
}
